#!/bin/sh /etc/rc.common
# /etc/init.d/clash
# Copyright (C) 2020 imKnect@Github
# For OpenWrt 19.07 gateway transparent proxy.

USE_PROCD=1
START=99
STOP=15

# CLASH_BIN=/etc/clash/clash
# CONFIG_PATH=/etc/clash
# CONFIG=/etc/clash/config.yaml

LOG=/tmp/clash.log

start_service()
{
	touch $LOG

	procd_open_instance main
	procd_set_param command /bin/sh -c "/etc/clash/clash -d /etc/clash >> /tmp/clash.log"
	procd_set_param respawn
	procd_set_param pidfile /var/run/clash.pid
	procd_close_instance

	add_iptables
	restore &
}

stop_service()
{
	sh /etc/clash/script/backup.sh

	if pidof clash >/dev/null; then
		kill $(pidof clash) || kill -9 $(ps | grep clash | grep -v grep | awk '{print $1}')
	fi

	rm_iptables
	rm -f $LOG
}

reload_service()
{
	rc_procd stop_service
	rc_procd start_service
}

boot()
{
	count=0
	while :
	do
		ping -c 1 -W 1 -q 223.5.5.5
		if [ "$?" == "0" ]; then
			break
		fi
		ping -c 1 -W 1 -q 114.114.114.114
		if [ "$?" == "0" ]; then
			break
		fi
		ping -c 1 -W 1 -q 119.29.29.29
		if [ "$?" == "0" ]; then
			break
		fi
		sleep 5
		count=$((count+1))
		if [ $count -gt 18 ]; then
			break
		fi
	done
	rc_procd start_service
}

service_triggers()
{
	procd_add_interface_trigger "interface.*.up" "wan" /etc/init.d/clash restart
}

add_iptables()
{
	ipset create localnetwork hash:net
	ipset add localnetwork 0.0.0.0/8
	ipset add localnetwork 10.0.0.0/8
	ipset add localnetwork 127.0.0.0/8
	ipset add localnetwork 169.254.0.0/16
	ipset add localnetwork 172.16.0.0/12
	ipset add localnetwork 192.168.0.0/16
	ipset add localnetwork 224.0.0.0/4
	ipset add localnetwork 240.0.0.0/4
	wan=$(ifconfig | grep 'inet addr' | awk '{print $2}' | cut -d: -f2 2>/dev/null)
	if [ ! -z "${wan}" ]; then
		for wan_ip in $wan; do
			ipset add localnetwork "$wan_ip4s" 2>/dev/null
		done
	fi

	ipset create proxy_lan hash:net
	ipset add proxy_lan 10.1.1.1/32
	ipset add proxy_lan 10.1.1.2/32
	ipset add proxy_lan 10.1.1.3/32
	ipset add proxy_lan 10.1.1.4/32
	ipset add proxy_lan 10.1.1.5/32
	ipset add proxy_lan 10.1.1.10/32

	iptables -t nat -N clash
	iptables -t nat -F clash
	iptables -t nat -A clash -m set --match-set localnetwork dst -j RETURN
	iptables -t nat -A clash -m set ! --match-set proxy_lan src -j RETURN
	iptables -t nat -A clash -p tcp -j REDIRECT --to-ports 7892
	iptables -t nat -A PREROUTING -p tcp -j clash

	ip rule add fwmark 1 table 100
	ip route add local default dev lo table 100
	iptables -t mangle -N clash
	iptables -t mangle -F clash
	iptables -t mangle -A clash -m set --match-set localnetwork dst -j RETURN
	iptables -t mangle -A clash -m set ! --match-set proxy_lan src -j RETURN
	iptables -t mangle -A clash -p udp -j TPROXY --on-port 7892 --tproxy-mark 1
	iptables -t mangle -A PREROUTING -p udp -j clash
}

rm_iptables()
{
	iptables -t nat -F clash >/dev/null 2>&1
	iptables -t nat -D PREROUTING -p tcp -j clash
	iptables -t nat -X clash >/dev/null 2>&1

	ip rule del fwmark 1 table 100 >/dev/null
	ip route del local default dev lo table 100

	iptables -t mangle -F clash >/dev/null
	iptables -t mangle -D PREROUTING -p udp -j clash
	iptables -t mangle -X clash >/dev/null

	ipset destroy proxy_lan >/dev/null
	ipset destroy localnetwork >/dev/null
}

restore()
{
	sleep 2
	sh /etc/clash/script/restore.sh 
}